# SPDX-FileCopyrightText: Copyright 2026, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

site_name: MLIA Neural Technology
site_description: Documentation for the MLIA Neural Technology target and backend plugin.
repo_url: https://github.com/arm/mlia-neural-technology
repo_name: arm/mlia-neural-technology
edit_uri: edit/main/docs/source/
docs_dir: docs/source
site_dir: .mkdocs/site
strict: true

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Target Profiles: target_profiles.md
  - Backends: backends.md
  - Outputs and Metrics: outputs_metrics.md
  - CLI: cli.md
  - Troubleshooting: troubleshooting.md
  - Development: development.md
