# SPDX-FileCopyrightText: Copyright 2024-2025, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: LicenseRef-LICENSE

target = "neural-technology"

[backend.nx-performance-estimator]
system_config = "system-config-neural-technology-default.ini"
compiler_config = "gc-config-neural-technology-default.ini"
