# SPDX-FileCopyrightText: Copyright 2023-2025, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: LicenseRef-LICENSE

target = "neural-technology"

[backend.nx-performance-estimator]
system_config = "peak-12SC-8NX-600MHz.ini"
compiler_config = "gc-config-upstream.ini"
