# SPDX-FileCopyrightText: Copyright 2023-2025, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: LicenseRef-LICENSE

target = "neural_technology"

[backend.nx-graph-compiler]
system_config = "sustained-12SC-8NX-350MHz.ini"
compiler_config = "gc-config-upstream.ini"
