; SPDX-FileCopyrightText: Copyright 2024-2025, Arm Limited and/or its affiliates.
; SPDX-License-Identifier: LicenseRef-LICENSE

; Compiler Configuration
[scheduler]
enableTensorPinning=false
enableSearchCascading=false
enablePairwiseStriping=false
