; SPDX-FileCopyrightText: Copyright 2024-2026, Arm Limited and/or its affiliates.
; SPDX-License-Identifier: LicenseRef-LICENSE

; Compiler Configuration
[scheduler]
enableTensorPinning=false
enableSearchCascading=true
enablePairwiseStriping=false
