# SPDX-FileCopyrightText: Copyright 2026, Arm Limited and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

name: Lint

on:
  workflow_call:

env:
  PYTHON_VERSION: "3.12"

  # Separate uv installations from each other on self-hosten runners
  # in case they share the working directory
  UV_CACHE_DIR: ${{ github.workspace }}/.uv-cache-ci-${{ github.run_id }}-${{ github.run_attempt }}
  UV_PROJECT_ENVIRONMENT: ${{ github.workspace }}/.venv-ci-${{ github.run_id }}-${{ github.run_attempt }}
  UV_TOOL_DIR: ${{ github.workspace }}/.uv-tools-ci-${{ github.run_id }}-${{ github.run_attempt }}
  UV_TOOL_BIN_DIR: ${{ github.workspace }}/.uv-bin-ci-${{ github.run_id }}-${{ github.run_attempt }}

  VAULT_COMMON_CI_SECRETS: &vault-common-ci-secrets |
    kv/data/MLIA/CI?version=${{ vars.VAULT_CI_SECRET_VERSION || '0' }} UV_DEFAULT_INDEX | UV_DEFAULT_INDEX ;
    kv/data/MLIA/CI?version=${{ vars.VAULT_CI_SECRET_VERSION || '0' }} INTERNAL_PYPI_USERNAME | UV_INDEX_INTERNAL_USERNAME ;
    kv/data/MLIA/CI?version=${{ vars.VAULT_CI_SECRET_VERSION || '0' }} INTERNAL_PYPI_PASSWORD | UV_INDEX_INTERNAL_PASSWORD ;
    kv/data/MLIA/CI?version=${{ vars.VAULT_CI_SECRET_VERSION || '0' }} VENDORED_ARTIFACTS_URLS | VENDORED_ARTIFACTS_URLS

jobs:
  lint:
    name: Lint
    runs-on: ["${{ vars.UBUNTU_RUNNER }}", "X64"]
    steps:
      - name: Import secrets from Vault
        # Vault secrets must not be exposed to pull requests from forks.
        if: >-
          ${{ github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository }}
        uses: hashicorp/vault-action@v4
        with:
          url: ${{ secrets.VAULT_URL }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          namespace: iac-expkits/prod
          secrets: *vault-common-ci-secrets
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Python development headers
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev
      - run: uv sync --group dev --no-install-project
      - run: uv run pre-commit run --all-files
